active_modules:
  PPD:
    module: UWBPPD
  iso15118_charger:
    module: D20Evse
    config_module:
      device: wlx4822542ce527
      private_key_password: "123456"
      enable_ssl_logging: true
    connections:
      PPD:
        - module_id: PPD
          implementation_id: main
    # config_module: 
    #   private_key_password: "failed"
    #   enable_ssl_logging: true
    #   tls_negotiation_strategy: ENFORCE_NO_TLS
  evse_manager:
    module: EvseManager
    config_module:
      connector_id: 1
      country_code: DE
      evse_id: DE*PNX*E12345*1
      evse_id_din: 49A80737A45678
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp/everest-logs
      charge_mode: DC
      hack_allow_bpt_with_iso2: true
      payment_enable_contract: false
    connections:
      bsp:
        - module_id: yeti_driver
          implementation_id: board_support
      powermeter_car_side:
        - module_id: powersupply_dc
          implementation_id: powermeter
      slac:
        - module_id: slac
          implementation_id: evse
      hlc:
        - module_id: iso15118_charger
          implementation_id: charger
      powersupply_DC:
        - module_id: powersupply_dc
          implementation_id: main
      imd:
        - module_id: imd
          implementation_id: main
  powersupply_dc:
    module: JsDCSupplySimulator
  yeti_driver:
    module: JsYetiSimulator
    config_module:
      connector_id: 1
  slac:
    module: JsSlacSimulator
  imd:
    module: IMDSimulator
  auth:
    module: Auth
    config_module:
      connection_timeout: 10
      selection_algorithm: PlugEvents
    connections:
      token_provider:
        - module_id: token_provider
          implementation_id: main
      token_validator:
        - module_id: token_validator
          implementation_id: main
      evse_manager:
        - module_id: evse_manager
          implementation_id: evse
  token_provider: 
    module: DummyTokenProvider
    config_implementation:
      main:
        token: TOKEN1
    connections:
      evse:
        - module_id: evse_manager
          implementation_id: evse
  token_validator:
    module: DummyTokenValidator
    config_implementation:
      main:
        validation_result: Accepted
        validation_reason: Token seems valid
        sleep: 0.25
  energy_manager:
    module: EnergyManager
    config_module:
      schedule_total_duration: 1
      schedule_interval_duration: 60
      debug: false
    connections:
      energy_trunk:
        - module_id: grid_connection_point
          implementation_id: energy_grid
  grid_connection_point:
    module: EnergyNode
    config_module:
      fuse_limit_A: 40.0
      phase_count: 3
    connections:
      price_information: []
      energy_consumer:
        - module_id: evse_manager
          implementation_id: energy_grid
      powermeter:
        - module_id: yeti_driver
          implementation_id: powermeter
x-module-layout: {}
